### ISSUE TITLE
Activities Not Triggered - Until restarted/refreshed/run locally

### ISSUE THREAD

**Issue by tbasallo** [Azure/azure-functions-durable-extension#1082]
I have a durable function that gets fired from a blob trigger. Four files a day.
Each one calls:
 - one activity to insert all records into SQL (async)
 - many single inserts into table storage using Task.WhenAll

Of the four, one is is about 30K records, the others from 1K - 4K.

If I run locally, all files (and many more files) are processed wihtout issue. I have run locally for a couple hours with no issues. 

Deployed to a consumption plan, the function pauses with activities in the queue that are never picked up. If I run locally, I can pick up what's pending. if I restart the job or refresh the job, it picks up where it was. I can see that there are over 32K items in a control queue (03)

It seems like it's falling asleep and just waits. It has waited for days before I released I had an issue. There are no errors or reporting that would indicate to me that something went wrong. I'm in the dark. The only reason I know is because I can query the DB and see that the records are not being inserted.

Additionally, there's only one server online (per live metrics stream). With these many items in queue, I would expect more serves to be spun up to help with the larger workload.

I've recreated a couple times unsure if it was a setting or outdated libs.

Using .net core 2.1
Azure durable functions 2.0
Functions extensions 1.0
webjob extensions 3.0.10
SDK 1.0.29

Latest failed instance aafe4a2a544d4e07bf6110b76e0e2706

**Comment by cgillum** [comment]
Hi @tbasallo. I think you may be running into two different issues:

* The fact that you aren't scaling appears to be caused by https://github.com/Azure/azure-functions-durable-extension/issues/1082. If you need a quick mitigation for this, consider downgrading from 2.0.0 to v1.8.3.
* The stuck instance part needs more investigation. I can see that 33206 out of 36507 completed on one VM. The remaining 3301 completed a little more than an hour later on a different VM around 2019-12-03 04:27:56 UTC.

Can you confirm that your orchestration is now completed? I'll continue to look at the latter issue to see what might have happened.

**Comment by tbasallo** [comment]
Hi @cgillum , it doesn't look like it's ended.
I still have 28K items in the *-control-03 queue

![image](https://user-images.githubusercontent.com/270673/70089368-ee6c7200-15e5-11ea-8fd2-be9b4af21939.png)

![image](https://user-images.githubusercontent.com/270673/70089462-22479780-15e6-11ea-81c1-b5adf3da95bd.png)

**Comment by tbasallo** [comment]
> Hi @tbasallo. I think you may be running into two different issues:
> 
> * The fact that you aren't scaling appears to be caused by #1082. If you need a quick mitigation for this, consider downgrading from 2.0.0 to v1.8.3.
> * The stuck instance part needs more investigation. I can see that 33206 out of 36507 completed on one VM. The remaining 3301 completed a little more than an hour later on a different VM around 2019-12-03 04:27:56 UTC.
> 
> Can you confirm that your orchestration is now completed? I'll continue to look at the latter issue to see what might have happened.

Which issue? #1082 is this one.

**Comment by cgillum** [comment]
Sorry, I meant https://github.com/Azure/azure-functions-durable-extension/issues/1064. I've edited my response to provide the right link.

**Comment by cgillum** [comment]
> I still have 28K items in the *-control-03 queue

Interesting. On closer inspection it looks to me like the Durable Functions trigger is failing to load the history for this orchestration instance. The last successful load of the history took over 250 seconds. This represents time spent reading rows from the history table where the partition ID matches the instance ID (aafe4a2a544d4e07bf6110b76e0e2706). After that I see a timeout exception and then nothing.

It actually seems like there has been latency issues reading this orchestration's history for quite a while. A few things to check:

1. Is the storage account you're using healthy? I'm wondering if this could be throttling.
2. Have you considered using [extended sessions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions)? This will radically reduce the amount of load being placed on your storage account.

We've definitely tested with more than 30K parallel activities before, but I'm not sure if those tests were run without extended sessions. Another potentially optimization you could try is to batch some of the activity function calls such that one activity function can do bulk inserts into SQL/table storage.

**Comment by tbasallo** [comment]
@cgillum How does one determine if storage is healthy?

I updated per your suggestions: hubname in host file and extended sessions. After publishing, the 28K items have started processing with no pause yet. Additionally, two servers are online now.

I'll report back tomorrow with how the files are processed. Today's files were processed locally.

![image](https://user-images.githubusercontent.com/270673/70114536-d0753080-162a-11ea-9cbc-305751e9634c.png)

**Comment by cgillum** [comment]
As far as determining if storage is healthy, there is some general guidance here: https://docs.microsoft.com/en-us/azure/storage/common/storage-monitoring-diagnosing-troubleshooting.

What I'm especially interested in knowing is if there are any logs indicating that the account is being throttled. I see there is an article that talks about this, but it's pretty old and I'm not sure if those directions are still applicable: https://blogs.msdn.microsoft.com/mast/2014/08/02/how-to-monitor-for-storage-account-throttling/

**Comment by tbasallo** [comment]
So the files did not kick off yesterday or today when the files were uploaded into blob storage. Checked now and they started up. I had to run locally to get them fully processed.

Is beta v3 suffering from the same issues? Wondering if rolling back to 1.8 or trying v3 is the way forward.

**Comment by tbasallo** [comment]
@cgillum , the changes made had no effect. I basically have files and activities stuck since the 6th of December. The worst part is I am not even sure I can stop 3 days of processing that will run in paralell since i have to run what I have to get caught up. :( 

Is v3 suffering from the same issues? Or os there a version I can build that this works correctly on?

I was hoping not to downgrade to 1.5 because the types changed and I'll have to make so many code changes.

**Comment by cgillum** [comment]
Sorry, I'm not sure what you're referring to when you say "v3" and "1.5". Can you clarify? For example, the _Azure Functions runtime_ has a 1.0, a 2.0, and a 3.0 preview. The latest supported versions of the _Durable Functions extension_ is either 1.8.3 or 2.0.0. I just want to make sure we're talking about the same things.

**Comment by tbasallo** [comment]
I thought there was a new durable lib to go along with the v3 runtime. I see that there isn't.

I upgraded to beta v3 on the runtime and I am running the 1.84 durable functions and I have had no issues for three days.

Is there an ETA on fixes for 2.0? The two issues seem critical to durable functions and I would say unusable for fan-in/fan-out scenarios.

**Comment by ConnorMcMahon** [comment]
@tbasallo,

It looks like this issue was because of #1068, which caused you to be affected by #1064. 

Now that #1068 is resolved, if you set a task hub (or use Functions V2), you should not be affected by #1064. I would recommend deploying to a test app and verifying.

**Comment by tbasallo** [comment]
Thanks, @ConnorMcMahon 

I'll close and re-open if not fixed.
