### ISSUE TITLE
Orchestration Trigger input binding fails with "Orchestration history state was either missing from the input or not a string value"

### ISSUE THREAD

**Issue by EmilDamsbo** [Azure/azure-functions-durable-extension#2804]
### Description
Running into the uncaught exception `"Orchestration history state was either missing from the input or not a string value"`. 

Setup
1. Have two functions F1 and F2, the first is an HTTP trigger and the other is an orchestrator function
2. HTTP trigger F1 schedules a new orchestration instance for F2, and [adds an additional input object ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.durabletask.client.durabletaskclient.scheduleneworchestrationinstanceasync?view=durabletask-dotnet-1.x#microsoft-durabletask-client-durabletaskclient-scheduleneworchestrationinstanceasync(microsoft-durabletask-taskname-system-object-microsoft-durabletask-startorchestrationoptions-system-threading-cancellationtoken))
3. Before my debugger enters F2, the input binding fails:
```
[2024-04-26T21:46:38.116Z] An error occurred while executing the orchestrator function 'DispatchJob'.
[2024-04-26T21:46:38.117Z] Result: An error occurred while executing the orchestrator function 'DispatchJob'.
Exception: System.InvalidOperationException: Orchestration history state was either missing from the input or not a string value.
[2024-04-26T21:46:38.118Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 55
[2024-04-26T21:46:38.119Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-26T21:46:38.120Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2024-04-26T21:46:38.121Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51Stack:    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in /_/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs:line 55
[2024-04-26T21:46:38.122Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 34
[2024-04-26T21:46:38.123Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2024-04-26T21:46:38.124Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51.
[2024-04-26T21:46:38.676Z] Executed 'Functions.DispatchJob' (Failed, Id=56e78500-0d6f-4448-880e-47e1b1d9571a, Duration=7706ms)
[2024-04-26T21:46:38.678Z] System.Private.CoreLib: Exception while executing function: Functions.DispatchJob. Microsoft.Azure.WebJobs.Extensions.DurableTask: Orchestration history state was either missing from the input or not a string value.
[2024-04-26T21:46:38.681Z] c663be9b1bde4b788c83378174a3bb1c: Function 'DispatchJob (Orchestrator)' failed with an error. Reason: Orchestration history state was either missing from the input or not a string value.. IsReplay: False. State: Failed. RuntimeStatus: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.13.2. SequenceNumber: 5. TaskEventId: -1
```
4.  I debugged, and it seems the orchestration trigger input binding is somehow binding a full object rather than a string in here:
  a.. https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/DurableTaskFunctionsMiddleware.cs#L49
  b. `triggerInputData` is expected to have a `.value` that is either null or string, but in my case it's a `{Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrationContext}`. The whole `triggerInputData` object after binding:
```
{
    "BindingMetadata": {
        "Name": "context",
        "Type": "orchestrationTrigger",
        "Direction": 0
    },
    "Value": {
        "IsAccessed": false,
        "Name": {
            "Name": "DispatchJob",
            "Version": ""
        },
        "InstanceId": "262ca4d6610f479da9e344d0681be433",
        "CurrentUtcDateTime": "2024-04-26T21:47:53.5989272Z",
        "IsReplaying": false,
        "Parent": null,
        "Entities": {}
    }
}
```

### Expected behavior
I expect the orchestration trigger to bind successfully, and start executing my function code.

### Actual behavior
`Function 'DispatchJob (Orchestrator)' failed with an error. Reason: Orchestration history state was either missing from the input or not a string value.`

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
I haven't encountered any workarounds yet.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: Microsoft.Azure.Functions.Worker.Extensions.DurableTask v 1.1.2
- **Azure Functions runtime version (1.0 or 2.0)**: V4,0
- **Programming language used**: C# ,NET 8 (isolated worker)

### Screenshots
![image](https://github.com/Azure/azure-functions-durable-extension/assets/67266681/004e2d8e-2ab3-448e-8a25-11636ff94861)

**Comment by cgillum** [comment]
This is incredibly strange. Does your app contain any customizations, like middleware, injected services, etc., - i.e. things that would normally be done in the Program.cs file?

I can't think of any reason why the trigger binding value would be an object, and why it would be a fully populated `FunctionsOrchestrationContext` of all things as shown in your screenshot.

It would be great if you could provide a minimal repro app for us to look at.

**Comment by EmilDamsbo** [comment]
We have quite a large app built around this, and there is potentially some middlewares at play. I'll work to produce a minimum repro of this within the week.
Some additional context would also be that the caller to the orchestrator is an abstract generic class which the entrypoint function inherits.

So something like
```
public abstract class FunctionBase<TRequest>
{
    protected async Task<IActionResult> DispatchJobFromRequest(TRequest request, DurableTaskClient context)
    {
        [...]
        // using the generated extension method for class-based orchestrators, but this reproed without it too
        // https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview#source-generator-and-class-based-activities-and-orchestrations
        await context.ScheduleNewDispatchJobInstanceAsync(request);
        [...]
        return new ObjectResult(...])
    }
}

public class RequestHandler : FunctionBase<MyRequest>
{
    [Function]
    public async Task<IActionResult> HandleRequest([HttpTrigger([...])] HttpRequest request, [DurableClient] DurableTaskClient context)
    {
        MyRequest convertedRequest = [convert HttpRequest to MyRequest somehow]

        return this.DispatchJobFromRequest(convertedRequest, context);
    }
}
```

And the orchestrator function DispatchJob is defined elsewhere _not_ inheriting from the `FunctionBase`.
This is the source-generated extension for the DurableTaskClient (censored the namespace and part of the object name), and I don't see any reason why it would pass the fully-formed `FunctionsOrchestrationContext` here. 
![image](https://github.com/Azure/azure-functions-durable-extension/assets/67266681/affeb9b0-519b-436b-83e9-8f9e7f5df3a4)

**Comment by cgillum** [comment]
@jviau can you take a look? This seems related to another issue that you've helped users with before.

**Comment by jviau** [comment]
@EmilDamsbo I imagine what happened is your source generation was eventually fixed, so that line: `new DurableTaskExtensionStartup().Configure(builder)` was now being implicitly called for you. Having that manual call wound up double registering our types, leading to some undefined behavior.

**Comment by EmilDamsbo** [comment]
I agree that this is most likely what happened after all my experimentation. Would it be possible to catch this DI double-registration on the durable extensions side or should I open an issue elswhere?

**Comment by jviau** [comment]
We could do some work on the durable side to make this registration re-enterable.

**Comment by lilyjma** [comment]
@EmilDamsbo - if you're still seeing the issue again, can you provide a latest minimal repro please? We'd like to know what exactly is the trigger of the exception. Thanks!

**Comment by cgillum** [comment]
Closing since the underlying issue has been fixed.

**Comment by MarcinJuraszek** [comment]
This issue still exists when using the new `IHostApplicationBuilder` logic being introduced right now (currently in -preview2 versions of Azure Functions). [The documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=ihostapplicationbuilder%2Cwindows#start-up-and-configuration) says to setup the host like this:

```
var builder = FunctionsApplication.CreateBuilder(args);

// (...) removed because doesn't seem to matter?

var host = builder.Build();
```

And later calls for `builder.ConfigureFunctionsWebApplication()` to be used to enable ASP.NET Core integration:

> If you want to use [ASP.NET Core integration](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=ihostapplicationbuilder%2Cwindows#aspnet-core-integration), call builder.ConfigureFunctionsWebApplication().

However, the moment you add that `ConfigureFunctionsWebApplication()` call, Durable Framework starts failing with:

>  Exception: System.InvalidOperationException: Orchestration history state was either missing from the input or not a string value.


To reproduce, simply create a new Azure Functions app with a Durable Function in it, update the SDKs to preview versions and change the host setup from 

```
var host = new HostBuilder()
    .ConfigureFunctionsWebApplication()
    .ConfigureServices(services =>
    {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .Build();

host.Run();
```

to

```
var hostBuilder = FunctionsApplication.CreateBuilder(args);

hostBuilder.ConfigureFunctionsWebApplication();

var host = hostBuilder.Build();

host.Run();
```

The versions I've used to reproduce it:

>     <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.0.0-preview4" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.4.0" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.7" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.0-preview4" />
>     <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.0-preview2" />

**Comment by cgillum** [comment]
Reactivating per @MarcinJuraszek as it seems like a new regression might have been introduced in some of the current preview nuget packages.

@jviau - any ideas what might be going on here?
